version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: dms
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: DMS

    volumes:
      - db_etc:/etc
      - db_var:/var

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: passwd
    ports:
      - "5080:80"
    depends_on:
      - db

volumes:
  db_etc:
  db_var:
